### ISSUE TITLE
process_queue triggered an exception

### ISSUE THREAD

**Issue by karolgebert** [wooky/ottd-prayer#1] opened 2022-08-27 11:11 UTC
Hi,

I get this error when trying to run the bot.

![image](https://user-images.githubusercontent.com/3704837/187027545-7ef6207b-f788-4015-9d5f-a9cb7f7ba8a0.png)

**Comment by wooky** [comment] 2022-08-27 11:22
Thanks for the bug report! Can you please post your yml configuration file? Or, at the very least, what version of OpenTTD the server is running?

**Comment by karolgebert** [comment] 2022-08-28 09:00
<pre>server:
  invite_code: "+KkZEhfU" # either this or server_host is REQUIRED
  player_name: "doopekk" # REQUIRED
  company_name: "WoodyWoodPacker LLC" # either this or company_id is REQUIRED
  server_port: 3979
  server_password: # default: unset
  company_password: "somePassword!" # default: unset

bot:
  # Go into spectator mode if the bot is the only player currently playing.
  # This is useful if you'd like the game to be paused when nobody is playing.
  spectate_if_alone: true

  # Connect back to the server if connection is lost or bot got kicked.
  auto_reconnect: true

  # How long to wait before reconnecting. Applicable only if auto_reconnect is set.
  auto_reconnect_wait: 30

  # How many times to try to reconnect before giving up and exiting.
  reconnect_count: 3

  # Should the bot reconnect if the game password is incorrect?
  auto_reconnect_if_wrong_game_password: false

  # Should the bot reconnect if the company name does not exist?
  auto_reconnect_if_company_not_found: false

  # Should the bot reconnect if it can't move to the specified company?
  # This can happen if the company does not exist, or password is incorrect.
  auto_reconnect_if_cannot_move: false

  # Should the bot reconnect if the server is shutting down?
  auto_reconnect_if_shutdown: false

  # Should the bot reconnect if the bot got banned?
  auto_reconnect_if_banned: false

  # Should the bot reconnect if the server is restarting?
  # Note that after restart, the company will, most likely, no longer exist.
  auto_reconnect_if_restarting: false

  # Bot log level. See https://docs.python.org/3/library/logging.html#levels for levels.
  log_level: DEBUG

ottd:
  network_revision: "12.2"
  revision_major: # default: derived from network_revision
  revision_minor: # default: derived from network_revision
  revision_stable: true
  coordinator_host: coordinator.openttd.org
  coordinator_port: 3976
</pre>

![image](https://user-images.githubusercontent.com/3704837/187066208-6d318297-5335-4cf5-95d1-558a0fb50b6d.png)

**Comment by karolgebert** [comment] 2022-08-29 18:15
Any news on this?

**Comment by wooky** [comment] 2022-08-29 18:49
> Any news on this?

I will let you know when I do some investigations on this.

**Comment by karolgebert** [comment] 2022-08-29 19:17
Ok, no problem. I am sorry, but I am just addicted to ottd :)

**Comment by karolgebert** [comment] 2022-09-06 16:40
I don't know if that might be useful, but I run ottd on GOG

**Comment by wooky** [comment] 2022-09-13 15:13
The problem is due to NewGRFs being present on the server, the bot chokes on them. I'll try to get the bot to support (and ignore) NewGRFs.

**Comment by karolgebert** [comment] 2022-09-13 15:23
Knowing what's the problem is a first step to solve it 😊 That's a great news, can't wait to use it :)

**Comment by wooky** [comment] 2022-09-13 17:12
Should be fixed now, please let me know the result.

**Closed as completed** 2022-09-13 17:12 UTC
Labels: bug

**Comment by karolgebert** [comment] 2022-09-13 17:55
Seems fine, thank you very much! :)
